### ISSUE TITLE
haw to push viedo en mp4 

### ISSUE THREAD

**Issue by drkamine** [hoangdh/ghichep-StreamingVideo#2]
hello  i can't push a mp4 viedo . 
 can please provied the step by step haw to push viedo and play it

**Comment by hoangdh** [comment]
What program are you using to streamming? 
Are you using nginx-rtmp?

**Comment by drkamine** [comment]
i use  nginx-rtmp in centos 7 .
i install it with this script 
https://github.com/hoangdh/ghichep-StreamingVideo/blob/master/nginx-rtmp/nginx-centos-7.sh

**Comment by drkamine** [comment]
i can't  push a viedo to rtmp by this command 
ffmpeg -i 04-Utiliser\ Hyper-V.mp4 -threads 1 -vcodec flv -acodec copy -s 1280x720 -f flv rtmp://192.168.1.84:1935/live/amine
 but i can't access by http

**Comment by hoangdh** [comment]
You can use OBS, Wirecat,... or ffmpeg to push your server.
With FFMpeg example:

```
ffmpeg -re -i video.mp4 -c copy -f flv rtmp://192.168.1.84:1935/live/amine
```

- `video.mp4` has been downloaded from YouTube.

Or see more about FFMPEG's guide: https://trac.ffmpeg.org/wiki/StreamingGuide

**Comment by drkamine** [comment]
thank you very much is work good , can please tell me haw i can see it in http://192.168.1.84/hls/amine/index.m3u8 , but i see only a download file named index.m3u8 with VLC

**Comment by hoangdh** [comment]
If you are web developer; you can use [JwPlayer](https://www.jwplayer.com/) or [hlsJS](https://github.com/video-dev/hls.js/) (OpenSource) on your web application.

In VLC, press CTRL + N and paste your stream URL and play. Enjoy!
